image: node:alpine

stages:
- build

Build:
  stage: build
  script:
    - apk install git
    - npm install -g yarn
    - cd /opt
    - git clone https://github.com/datopian/frontend-v2.git
    - cd frontend-v2
